---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.14.4
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python:
    - six
    - psutil
  system: bindep.txt

images:
  base_image:
    name: docker.io/redhat/ubi9:latest

options:
  package_manager_path: /usr/bin/dnf

additional_build_files:
  - src: files/microsoft-prod.repo
    dest: configs

additional_build_steps:
  prepend_base:
    - RUN echo Adding Microsoft Repository to Image
    - COPY _build/configs/microsoft-prod.repo /etc/yum.repos.d/

  append_final:
    - RUN echo Post Install
    - RUN ls -al /etc/yum.repos.d
