- name: Gather Storage Information
  hosts: localhost
  connection: local

  tasks:
    - name: Include gather_data role
      ansible.builtin.include_role:
        name: gather_data

    - name: Print storage_data
      ansible.builtin.debug:
        var: storage_data

    - name: Process storage systems
      ansible.builtin.include_role:
        name: process_data
      loop: "{{ storage_data | dict2items }}"
      loop_control:
        loop_var: storage_array
