- name: Debug Storage Array
  ansible.builtin.debug:
    var: storage_data
    verbosity: 1

- name: Extend Disk if disk_percent exceeds threshold
  ansible.builtin.include_tasks: extend.yml
  loop: "{{ storage_data | dict2items }}"
  loop_control:
    loop_var: storage_disk
