---
all:
  children:
    storage_servers:
      children:
        critical:
          hosts:
            storage1:
              ansible_connection: local
            storage2:
              ansible_connection: local
        standard:
          hosts:
            storage3:
              ansible_connection: local
            storage4:
              ansible_connection: local
