---
all:
  children:
    # create storage_servers group with 2 child groups - critical and standard
    storage_servers:
      children:
        # create 'hosts' that are actually just aliases to a local connection for demonstration purposes
        critical:
          hosts:
            storage1:
              ansible_connection: local
            storage2:
              ansible_connection: local
        standard:
          hosts:
            storage3:
              ansible_connection: local
            storage4:
              ansible_connection: local
