- name: Gather Data from Fake Storage Devices
  ansible.builtin.set_fact:
    storage_data: "{{ storage_data | d({}) | combine({item: {'disk_percent': (100 | random), 'disk_size': (10000000 | random | string) + ' bytes'}}) }}"
  loop:
    - storage1
    - storage2
    - storage3
    - storage4
