---
## This is play 1
- name: Install and enable apache webserver
  hosts: web
  become: true
  tasks:
    - name: Install Python Library for Firewall Management
      ansible.builtin.package:
        name: python3-firewall
        state: present

    # Install apache webserver & open firewall port 80 for the webserver &  create a custom index.html file that has "I'm a custom website" as content & start the service
